# Generated by Django 6.1.1 on 2026-09-18 07:54

import contract.educational_content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('educational-content', 'Educational Content')], default='educational-content', max_length=64)),
                ('agreement_number', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('additional_courses', models.TextField(blank=True, default='')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('text', 'Text'), ('table', 'Table'), ('', 'None')], default='', max_length=16)),
                ('payment_text', models.TextField(blank=True, default='')),
                ('quarterly_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('disbursement', models.CharField(blank=True, default='', max_length=255)),
                ('budget_type', models.CharField(choices=[('current', 'Current'), ('investment', 'Investment')], default='current', max_length=16)),
                ('contract_text', models.TextField(blank=True, default='')),
                ('is_hidden', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=contract.educational_content.models.UploadToPath)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('stored_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'educational_contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='contract.educationalcontent')),
            ],
            options={
                'db_table': 'educational_content_payment_schedule',
                'ordering': ['order'],
            },
        ),
    ]
